spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/weixin?useSSL=false&serverTimezone=CST
      username: root
      password: 1234
   
   redis:
      host: 112.74.53.29
      prot: 6379
      database: 15